create table FROG_SIDE_MENU_TB (
SIDE_NAME          VARCHAR2(60)    PRIMARY KEY,
SIDE_PRICE         NUMBER(10)      CHECK (SIDE_PRICE >= 0), 
SIDE_KCAL          NUMBER(10,2)    CHECK (SIDE_KCAL >= 0), 
SIDE_COOK          VARCHAR2(30),
SIDE_POPULARITY    NUMBER(10)
);

commit;