create table FROG_DRINK_MENU_TB (
DRINK_NAME          VARCHAR2(60)    PRIMARY KEY,
DRINK_PRICE         NUMBER(10)      CHECK (DRINK_PRICE >= 0), 
DRINK_KCAL          NUMBER(10,2)    CHECK (DRINK_KCAL >= 0), 
DRINK_POPULARITY    NUMBER(10)
);

commit;